### ISSUE TITLE
AssertionError: You need exactly one of "params" or "text" in field postData

### ISSUE THREAD

**Issue by OOXXXXOO** [louisabraham/har2requests#13]
AssertionError: You need exactly one of "params" or "text" in field postData

**Comment by louisabraham** [comment]
> When encountering errors, you can use the --unsafe feature that will display warnings instead of errors if the HAR file does not fit the specification (it happens a lot).

did you try?

**Comment by coolkidmacho** [comment]
I got the same error, i tried the unsafe feature. The output file is empty.

**Comment by netchose** [comment]
hi,
same problem for me but ok with the unsafe parameter

**Comment by louisabraham** [comment]
The unsafe is there to abide the specifications. I should probably change the default to always use it and provide a `--safe` parameter.

**Comment by louisabraham** [comment]
If you want `--unsafe` to be the default, upvote this comment.

**Comment by OOXXXXOO** [comment]
i change the source code ”assert“ function that could work just for now. Hope the aurthor could fix this issue forever

**Comment by louisabraham** [comment]
@OOXXXXOO is this assert disabled by "unsafe" ?

**Comment by louisabraham** [comment]
I disabled this behavior as it seems that browsers don't respect this part of the HAR specs.
