### ISSUE TITLE
Getting blank output

### ISSUE THREAD

**Issue by ermannoff** [louisabraham/har2requests#19]
For some reason I am getting blank output for some har files. The har file is not that big in size so that possibility should be excluded. The processing is happening normally. But after processing complete the output file  is blank

**Comment by louisabraham** [comment]
Maybe it's an issue with your terminal? Try to redirect to a file.
Can you provide a minimum reproducible example?

**Comment by tarunmudgal** [comment]
[console-stg.cloud.vmware.com_Archive.har.zip](https://github.com/louisabraham/har2requests/files/10109957/console-stg.cloud.vmware.com_Archive.har.zip)
I also faced the same issue. Below is the console output of har2requests utility. Output file test.py remains empty. I'm attaching the  here for reference. Please have a look once.

(venv3.8) mtarun@mtarun-a01 utilities % sudo ../../venv3.8/bin/har2requests --exclude-cookie-headers --unsafe ~/Downloads/console-stg.cloud.vmware.com_Archive.har > test.py
/Users/mtarun/OneDrive_VMware_Inc/vmware/code/mangle-yaan-service/venv3.8/lib/python3.9/site-packages/har2requests/request.py:95: UserWarning: content size > 0 but responseText is empty
  warnings.warn("content size > 0 but responseText is empty")
Inferring header origin. If it's slow, try --no-infer.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 127/127 [00:11<00:00, 11.01it/s]
(venv3.8) mtarun@mtarun-a01 utilities %

**Comment by louisabraham** [comment]
Hi, I definitely cannot reproduce. It gives me a Python code with 23797 lines.

```
louisabraham@mbpla ~ % har2requests --exclude-cookie-headers --unsafe /Users/louisabraham/Downloads/console-stg.cloud.vmware.com_Archive.har | wc -l
/Users/louisabraham/code/har2requests/har2requests/request.py:95: UserWarning: content size > 0 but responseText is empty
  warnings.warn("content size > 0 but responseText is empty")
Inferring header origin. If it's slow, try --no-infer.
100%|█████████████████████████████████████████████████| 127/127 [00:06<00:00, 19.30it/s]
   23797
```

**Comment by LaoshuBaby** [comment]
I meet with blank file issue again

![image](https://github.com/louisabraham/har2requests/assets/42690037/30f8134c-1799-493e-a34b-5d8d4da03c24)

```
D:\Git\geo-yuheng>har2requests input.har > output.py
Inferring header origin. If it's slow, try --no-infer.
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.03it/s]
```
[mnc.qiuwenbaike.cn.har.zip](https://github.com/louisabraham/har2requests/files/14751952/mnc.qiuwenbaike.cn.har.zip)

@louisabraham

**Comment by LaoshuBaby** [comment]
> I meet with blank file issue again
> 
> ![image](https://private-user-images.githubusercontent.com/42690037/316715448-30f8134c-1799-493e-a34b-5d8d4da03c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjM2MDQsIm5iZiI6MTcxMTQyMzMwNCwicGF0aCI6Ii80MjY5MDAzNy8zMTY3MTU0NDgtMzBmODEzNGMtMTc5OS00OTNlLWEzNGItNWQ4ZDRkYTAzYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzMjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNzZiMjRlMmIwYWFkMDlhOGMyNTNjZGU4NGUwYjUyNzlhYjQ3MTEwMTBjZWZkMjc2ODJkOTVkOTc1MWU0M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fqI2UMPL8qs9NHUxPLlfcemJ5WRXcUqKO-QBBVUSLS8)
> 
> ```
> D:\Git\geo-yuheng>har2requests input.har > output.py
> Inferring header origin. If it's slow, try --no-infer.
> 100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.03it/s]
> ```
> 
> [mnc.qiuwenbaike.cn.har.zip](https://github.com/louisabraham/har2requests/files/14751952/mnc.qiuwenbaike.cn.har.zip)
> 
> @louisabraham

My fault, don't use Windows, I should use WSL instead

![图片](https://github.com/louisabraham/har2requests/assets/42690037/4886b359-b4b6-40d3-8935-d13463184bfe)
