### ISSUE TITLE
dash/hyphen in variable name

### ISSUE THREAD

**Issue by dragancevs** [louisabraham/har2requests#3]
Hi, the package generates python scripts where are dashes/hyphens in variable names, content type. So python shows  syntax error. I use python 3.7 .

> Content-type_1

**Comment by louisabraham** [comment]
Good catch, I'll try to fix that. Can you provide more context (like logs)?

**Comment by louisabraham** [comment]
@spider-x I'm closing this for the moment, don't hesitate to reopen if you still have the problem and can provide a http://sscce.org/!
