### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by asdaragon** [louisabraham/har2requests#5]
it is very nice module, but when i use it transfer to python file, it have error response:

![image](https://user-images.githubusercontent.com/22835918/81810847-44aaed00-9556-11ea-939d-ffa0531cabfb.png)

how can i solve it?

**Comment by RobertSchultzeAuticon** [comment]
your error report would be more helpful, if it also included the relevant part of the input.har (does it contain {"log": { "entries": ...} ?)
the error message reads as if your input.har is not the original generate .har from your browser

**Comment by ice1x** [comment]
> your error report would be more helpful, if it also included the relevant part of the input.har (does it contain {"log": { "entries": ...} ?)
> the error message reads as if your input.har is not the original generate .har from your browser

same for me,
har generated by chrome,

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
- log are present

**Comment by ice1x** [comment]
TypeError: string indices must be integers
using har generated by Google Chrome

**Comment by louisabraham** [comment]
Please provide a traceback and a reproducible example

**Comment by AdrieVanDijk** [comment]
I have have the same problem, har-file (chromium, zipped) and console output attached.

[garmin-login-chromium.zip](https://github.com/louisabraham/har2requests/files/5056721/garmin-login-chromium.zip)
[console-output.txt](https://github.com/louisabraham/har2requests/files/5056632/console-output.txt)

ubuntu 20.4, python 3.8.2

**Comment by noelslice** [comment]
Same issue here too. Great module though!

**Comment by louisabraham** [comment]
I'll look at it. In the case your issue was a bit different, do you mind attaching the file and a traceback?

**Comment by louisabraham** [comment]
Try the latest version with `--unsafe` :smile:

**Comment by noelslice** [comment]
Woo-hoo! Thanks @louisabraham, it's working now with `--unsafe`
