### ISSUE TITLE
adherence to har spec

### ISSUE THREAD

**Issue by RobertSchultzeAuticon** [louisabraham/har2requests#6]
http://www.softwareishard.com/blog/har-12-spec/#postData

if i have a har containing

```
"postData": {
            "mimeType": "application/json",
            "text": "snip"
}
```

which fails with 

```
[...]__init__.py", line 64, in from_json
    postData=Request.dict_from_har(request["postData"]["params"])
KeyError: 'params'
```

Which is expected since text is mutually exclusive with params

**Comment by louisabraham** [comment]
Note: you can use ` ``` ` to escape blocks of code
